### ISSUE TITLE
Beautify badbrowser.html

### ISSUE THREAD

**Issue by TheAwesome98-Real** [strukturart/telegram-kaios#1]
It’s hard to read, if we want to change it for some reason, it’d be hard to do so. Just google HTML Beautifier and you can find one to do that.

**Comment by strukturart** [comment]
I think the file can be deleted if you use the app with KaiOs.

**Comment by TheAwesome98-Real** [comment]
Oh okay, is this a direct fork? Anyway,
CLOSED: i made a pull request of it
