### ISSUE TITLE
Cant login / stay logged in

### ISSUE THREAD

**Issue by flaep** [strukturart/telegram-kaios#4]
Hi,

i tried your app but I do not stay logged in. After providing the code iam back at the country menu
Is this app still supposed to work?

Iam running gerdaOS 13.

thank you

**Comment by strukturart** [comment]
yes it works, after each reinstallation you have to log in again.

**Comment by flaep** [comment]
Thanky you for your quick reply.
What could be the reason that I not stay logged in? I downloaded the zip in the build folder.


While providing my phone number i also getting a pop up about setting a alarm. Happens when pressing "1".

**Comment by strukturart** [comment]
okay I will fix this......
pls download/install again

**Comment by flaep** [comment]
That was fast.

Trying right now

**Comment by strukturart** [comment]
someone in reddit community is currently working on a modified version -> https://www.reddit.com/r/KaiOS/comments/huhfj2/update_telegram_on_kaios/

I haven't tested it yet, but the navigation may have been improved

**Comment by flaep** [comment]
I also found that one. But since it hosted on some One Click Hoster that requires login. It appears not very trustworthy

**Comment by strukturart** [comment]
now it works with the login ?

**Comment by flaep** [comment]
It does not work. 
I recorded a [video](https://youtu.be/OKwfYVPdVGc).

**Comment by strukturart** [comment]
it looks like the telgram client is no longer working: 
https://github.com/zhukov/webogram

**Comment by flaep** [comment]
so its a webogram on Kaios issue?

Thank you for your time

**Comment by strukturart** [comment]
I unfortunately after I uninstalled telegram and reinstalled the same problem. web.telegram.org doesn't work anymore, but web.telegram.im does, but unfortunately don't know the difference. did you install the current version of gerda?

**Comment by flaep** [comment]
according to the phone iam running 13.00.17.01 its a 8110 4g

Checking for gerda updates right now.

**Comment by strukturart** [comment]
Unfortunately I could not find a solution so far, so I wrote a web wrapper that loads as iframe web.telegram.im. However, the operation is very, very limited. you can find the "app" in / build

**Comment by flaep** [comment]
Going to test later.
Using web.telegram.im in browser works reliable.

**Comment by flaep** [comment]
Feedback:

I cant scroll in the app and cant therefore type in the verification code. It also schedules an alarm again.

**Comment by strukturart** [comment]
you has to click on send by sms than you can enter the code
